### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Enorya** [asrivathsan/ONTbarcoder#1]
Hi @asrivathsan, I'm trying to use ONTbarcoder in order to demultiplex my reads sequenced with MinION sequencer but I have one problem. I cloned your github repository and I tried to launch ONTbarcoder with this command: `python ONTbarcoder.py` and I get this error: 
```python
    print os.path.join(self.outdir,"identicalbarcodes_658chosen.fa")
           ^
SyntaxError: invalid syntax
```
I'm working on a linux system with ubuntu 16.04
Do you have any idea what is the problem? Am I doing something wrong?

**Comment by asrivathsan** [comment]
Hello,

I believe this is happening because the software is being run as a script. It has been packaged as executable with GUI for linux as well; available in the releases tab in this repository: https://github.com/asrivathsan/ONTbarcoder/releases . You can double click the ONTbarcoder executable from the downloaded package for your OS.

Best wishes
Amrita

**Comment by Enorya** [comment]
It works, thanks!
