### ISSUE TITLE
No output from consensus calling 

### ISSUE THREAD

**Issue by imanamoeba** [asrivathsan/ONTbarcoder#6]
Hi there,
I have conducted a test sequencing run on our MinION using the ONT's rapid barcoding kit. I am inputting demultiplexed fasta files into ONTBarcoder on my Mac, as per the second option. Unlike the Diptera sample data, the run with my data of interest completes almost instantly, and does not generate any output, though the number of reads is detected. The log file is pasted below. The sample of interest contained snail COI amplicon. I have tried other runs using different coverage parametres and length of the barcode, and also another COI sample sequenced within the same library, no luck though. I am guessing that the sequencing data itself is the problem, but I thought I would post on here in case there are any troubleshooting steps I should try. Please let me know if sending a sample input file and further info would be helpful. Thanks in advance for any thoughts on this.
Kind regards,
Bonnie

Input folder of demultiplexed reads: /Users/**/Desktop/ONTBarcoder/Barcode3_fa/
Length of barcode: 658<br>Window to select reads of long length after demultiplexing: 50
Coverage used for barcode calling based on subsetting reads by lengths: [25, 50, 100, 200, 500]
Coverage used for barcode calling in 2nd step, based on subsetting reads by similarity: 100
Genetic code: 5
1649130029.0: Consensus calling based on sequences closest to length reads is complete

Consensus sequences are stored in /Users/**/Desktop/ONTBarcoder/6/barcodesets/consensus/consensus_all_step1.fa.1649130029.0: Reading the MSA to split the barcodes post length, translation and internal gap check. 
Results are saved in /Users/**/Desktop/ONTBarcoder/6/barcodesets/predgood/consensus_predgood_barcodes.fa 
and /Users/**/Desktop/ONTBarcoder/6/barcodesets/pred_erroneous/consensus_prederr_barcodes.fa
1649130029.0: No good consensus barcode found in first round, trying now with reads closest to the first consensus
1649130030.0: Second consensus calling completed
1649130030.0: Reading the MSA to split the barcodes post length, translation and internal gap check. 
Results are saved in /Users/**/Desktop/ONTBarcoder/6/barcodesets/consensus_by_similarity/90perc_predgood_barcodes.fa 
and /Users/**/Desktop/ONTBarcoder/6/barcodesets/consensus_by_similarity/90perc_prederr_barcodes.fa
Number of good barcodes based on 90% matching=0
1649130030.0: Alignments for fixing barcodes is complete
1649130030.0: Fixed barcodes are generated
1649130030.0: The pipeline is completed. 0 consensus barcodes have been built.
Please check /Users/**/Desktop/ONTBarcoder/6/Main_barcode_results for the final output

**Comment by asrivathsan** [comment]
Hello, 

Yes a sample file would be helpful. You could mail it to me asrivathsan@gmail.com in case you don't want it public.

Thank you
Amrita

**Comment by imanamoeba** [comment]
Hi Amrita,
Thanks for your reply. I have attached a zipped folder containing the first two fasta files that I am inputting into ONTBarcode. These are fasta files converted from fastq files which epi2me demultiplexed. 

I am also attaching the dem file that I tried when trialling the fastq option (same problem with consensus calling), note I have inserted the ONT rapid barcode sequence twice as this was the only tag I used for this sample. 

Extra info: This sample's PCR product seemed fine when I ran it on a gel, and was incorporated into the rapid barcode library at a concentration of 20ng/ul, so I would have thought it would sequence ok despite the fact that our flowcell had been used before. Another sample in this library contained 16S PCR product and this seemed to produce reasonable results when I ran in through ONT's WIMP pipeline.

Thanks!
Cheers,
Bonnie

[MinION_melanoides_demfile.txt](https://github.com/asrivathsan/ONTbarcoder/files/8421295/MinION_melanoides_demfile.txt)

[Barcode3_test_fa.zip](https://github.com/asrivathsan/ONTbarcoder/files/8421246/Barcode3_test_fa.zip)

**Comment by asrivathsan** [comment]
Thank you for sharing this. I believe the tags used in your study are quite long, and ONTbarcoder was tuned to use shorter tags (I think <15 should be optimal). This is because the focus was very much on highly multiplexed datasets. It allows for only 2 bp errors, and the tags must be present on both sides. it doesn't therefore surprise me if demultiplexing doesnt work well, and it may be best to use demultiplexing solutions provided by ONT given its kit was used, and not the tags that were provided in the ONTbarcoder manuscript.

Can I know the estimated barcode length for the demultiplexed datasets? If exact lengths are not known thats fine.

**Comment by imanamoeba** [comment]
Thanks, that's good to know re: demultiplexing. Our lab is hoping to move to barcoding 96 well plates with non ONT barcodes, so this is will be useful for planning library prep and analysis in the future. 

I have looked through genbank and the literature for the snail Melanoides tuberculata, and am expecting that the barcode should be approximately 650 bp long. I have seen 638, 642 and 658 bp reported for this primer-species combination. Our sample may also contain sequences from an unknown trematode parasite, which would most likely be around the 600-650 bp range. Folmer primers don't always work with these helminths however, so perhaps these sequences just aren't there.

**Comment by asrivathsan** [comment]
Hello,

I think the pipeline works on your files once you convert them to non-interleaved fasta. You can use this script if you would like to batch convert them. 
[reformat.py.zip](https://github.com/asrivathsan/ONTbarcoder/files/8453121/reformat.py.zip)

usage is

python reformat.py inputdirectory_containing_fasta outputdirectory

the outputdirectory should be an empty directory

However, i cannot assure you the quality of barcodes based on the current data. The issue is the raw reads don't seem to be length restricted and seem to vary a lot by length. All our pipeline is optimized hac + ligation sequencing, perhaps the quality of data varies a lot more.  You can try and see if playing with parameters can help you achieve better success.

If you are planning to do 96+ samples, using the tagged primers supplied in the ONTbarcoder manuscript along with the dual tagging strategy and protocol described should yield good results. Hope all goes smoothly now.

**Comment by imanamoeba** [comment]
Thank you for looking into that issue, and for your patience with a non-protocol dataset, it is much appreciated. The non-interleaved format seems to work, and the barcode sequences generated by the consensus by length are consistent with what is expected from this sample, hooray! As you pointed out, sequence and resulting consensus quality is an issue as no barcodes (even ones that fail QC) are called in steps 2B and 2C. I will experiment with different parameters as you have suggested.

FYI, I encountered a minor issue when running the program. For one sample ONTBarcoder generated consensus by length barcodes at 25X and 50X coverage just fine. It did however hang indefinitely at the 100X consensus by length stage. The progress bar stayed at 0% and no output was generated for this coverage. When I restarted the run with a lower coverage, i.e. 75X as the third and final coverage , the run completed normally. Presumably this is caused by the absence of consensus barcodes with a coverage of 100X?

**Comment by asrivathsan** [comment]
Thanks a lot for the feedback. Regarding the 100X coverage, your data coverage should not hang the software. however, on rare occasions if you are running multiple softwares on the computer and threads are busy, there is a possibility software freezes. If you face this problem repeatedly please let me know, I will look into it.
