### ISSUE TITLE
Degenerate primers and inosines

### ISSUE THREAD

**Issue by OndroV** [asrivathsan/ONTbarcoder#9]
Hi Amrita,

I'm wondering how to apply ONTbarcoder when using degenerate primers. Many samples require that we use **jj** or **jg** versions of LCO-HCO. The widespread Cutadapt tool suppports primer degeneracy, so it would be a pity if ONTbarcoder did not.
The manual mentions this only by "_At least, tags should be removed if primers do not have ambiguous bases_" (page 2) and I can't interpret this as a clear information about (in)compatibility of degenerate primers with ONTbarcoder. Then in [this issue](https://github.com/asrivathsan/ONTbarcoder/issues/3#issuecomment-846956981) you mention that they will cause issue. Is that a major issue? Could we overcome it by somehow running the demultiplexing with all possible combinations of degenerate bases :D ? Or is there another way? 

Also, the jg version of LCO-HCO contains inosines, which might be important for successful high-throughput barcoding. Do you know what the basecalling outputs for such sequences and how ONTbarcoder handles them, please? I couldn't find any useful info from nanopore ([link to my post there](https://community.nanoporetech.com/posts/inosine-in-nanopore)).

Looking forward to trying this new version of ONTbarcoder soon!
Ondrej

jgLCO1490: TITCIACIAAYCAYAARGAYATTGG
jgHCO2198: TAIACYTCIGGRTGICCRAARAAYCA

**Comment by asrivathsan** [comment]
Hi Ondrej,

Degenerate primers work perfectly fine with ONTbarcoder, the question in how the samples were multiplexed. It is tailored to demultiplexing if you have custom tags of the nature we have described in the ONTbarcoder manuscipt, not extremely long tags/indices

The comment on the manual refers to how one could deal with "tag-less" amplicons. but this is not the best practice... becase primers may make the molecule untranslatable. 

You can replace "I" in inosine as N because from my understanding it binds to all four nucleotides, and thus the jgHCO2198 can be input as TANACYTCNGGRTGNCCRAARAAYCA

Hope this helps!
cheers
Amrita
